# Get Node image, install dependencies and cache node_modules.
.node: &node
  image: node:latest
  before_script:
    - npm install
  cache:
    key: '$CI_COMMIT_REF_NAME' # Set by the Runner an environment variable.
    paths:
      - node_modules/

# Define a deployment stage.
stages:
  - deploy

# Deployment settings.
deploy:
  # Deployment staage with 'development' environmental variable.
  stage: deploy
  environment:
    name: development

  <<: *node # Job definition.
  script:
    - npm run build -- -e $CI_ENVIRONMENT_SLUG # Will use 'development' as a $CI_ENVIRONMENT_SLUG environmental variable.
    - npm run deploy # Deploy to Firebase hosting.
  only:
    - master # Corresponding to the production environment and only the master branch. The project could have separated branch for development.

# Production settings.
production:
  # Deployment stage with 'production' environmental variable.
  stage: deploy
  environment:
    name: production

  <<: *node # Job definition.
  script:
    - npm run build -- -e $CI_ENVIRONMENT_SLUG # Will use 'production' as a $CI_ENVIRONMENT_SLUG environmental variable.
    - npm run deploy # Deploy to Firebase hosting.
  only:
    - master # Corresponding to the production environment and only the master branch.
# TODO: Add test stage.
