# Get Docker image containing Firebase CLI for deployments to Firebase.
image: devillex/docker-firebase

# Cache node_modules.
cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

# Define a deployment stage.
stages:
  - deploy

# Deployment settings.
deploy:
  stage: deploy
  environment:
    name: development # Deployment stage for development environment.
    # name: production # Deployment stage for development environment.
  script:
    - npm install
    - npm run build
    - npm run deploy
  only:
    - master # Corresponding only to the master branch.

# TODO: Add test stage.
